name: Deploy to production

on:
  push:
    branches: [ master ]

jobs:

  build:
    name: Build images
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Login to Aliyun docker repository
        run:
          docker login --username=${{ secrets.ALIYUN_USERNAME }}  --password=${{ secrets.ALIYUN_PASSWORD }} registry.cn-hangzhou.aliyuncs.com

      - name: Build, tag, and push image to Amazon ECR
        env:
          REGISTRY: ${{ secrets.REGISTRY }}
          REPOSITORY: ${{ secrets.REPOSITORY }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
