name: Deploy to production

on:
  push:
    branches: [ master ]

jobs:

  build-and-deploy:
    name: Build image and deploy to k8s
    runs-on: ubuntu-latest
    env:
      REGISTRY: ${{ secrets.REGISTRY }}
      REPOSITORY: ${{ secrets.REPOSITORY }}
      IMAGE_TAG: ${{ github.sha }}

    steps:
      - uses: actions/checkout@v2

      - name: Login to Aliyun docker repository
        run:
          docker login --username=${{ secrets.ALIYUN_USERNAME }}  --password=${{ secrets.ALIYUN_PASSWORD }} registry.cn-hangzhou.aliyuncs.com

      - name: Load secrets and save to app.env
        run: |
          echo DB_DRIVER=${{ secrets.DB_DRIVER }} > app.env
          echo DB_SOURCE=${{ secrets.DB_SOURCE }} >> app.env
          echo SERVER_ADDRESS=${{ secrets.SERVER_ADDRESS }} >> app.env
          echo TOKEN_SYMMETRIC_KEY=${{ secrets.TOKEN_SYMMETRIC_KEY }} >> app.env
          echo ACCESS_TOKEN_DURATION=${{ secrets.ACCESS_TOKEN_DURATION }} >> app.env

      - name: Build, tag, and push image to Aliyun
        run: |
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG

      - name: Modify deployment.yaml
        run: |
          sed -i 's!{REGISTRY}!'$REGISTRY'!g' k8s/deployment.yaml
          sed -i 's!{REPOSITORY}!'$REPOSITORY'!g' k8s/deployment.yaml
          sed -i 's!{IMAGE_TAG}!'$IMAGE_TAG'!g' k8s/deployment.yaml

      - name: Deploy image to k8s
        uses: steebchen/kubectl@master
        with:
          config: ${{ secrets.KUBE_CONFIG_DATA }}
          version: v1.22.0
          command: apply -f k8s/deployment.yaml

      - name: Verify deployment
        uses: steebchen/kubectl@master
        with:
          config: ${{ secrets.KUBE_CONFIG_DATA }}
          version: v1.22.0
          command: rollout status deployment/simple-bank-api-deployment

      - name: Create service
        uses: steebchen/kubectl@master
        with:
          config: ${{ secrets.KUBE_CONFIG_DATA }}
          version: v1.22.0
          command: apply -f k8s/service.yaml
