name: Deploy to production

on:
  push:
    branches: [ master ]

jobs:

  build:
    name: Build images
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Login to Aliyun docker repository
        env:
          aliyun-username: ${{ secrets.ALIYUN_USERNAME }}
          aliyun-password: ${{ secrets.ALIYUN_PASSWORD }}
        run:
          docker login --username=$aliyun-username  --password=$aliyun-password registry.cn-hangzhou.aliyuncs.com

      - name: Build, tag, and push image to Amazon ECR
        env:
          REGISTRY: ${{ secrets.REGISTRY }}
          REPOSITORY: ${{ secrets.REPOSITORY }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
